name: Backup Repository

on:
  schedule:
    - cron: '0 22 * * *'  # Run every day at 22:00 PM UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  backup:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Check dist directory
        run: |
          echo "Checking dist directory"
          ls -la dist

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH key
        run: ssh-add -L

      - name: Check connection to remote server
        run: |
          echo "Checking connection to remote server..."
          ssh -vvv -p 2222 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no msalsouri@msalsouri.duckdns.org 'echo "Connection successful"'

      - name: Rsync files
        run: |
          echo "Starting Rsync..."
          rsync -avz -e "ssh -p 2222 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" ./dist/ msalsouri@msalsouri.duckdns.org:~/Projects/WordPress-Plugins-Dev/hoi-wp-plugins-dev/wp-content/
          echo "Rsync completed."

      - name: Push to Backup Repository
        run: |
          echo "Checking if backup remote exists..."
          if git remote | grep backup; then
            echo "Removing existing backup remote..."
            git remote remove backup
          fi
          echo "Adding backup remote..."
          git remote add backup git@github.com:hoiltd/hoi-wp-plugins-dev-backup.git
          echo "Pushing to backup repository..."
          git push backup main --force

