name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "/"  # Change this if you want to deploy different directory
          REMOTE_HOST: "msalsouri.duckdns.org"  # Replace with your server's IP address
          REMOTE_USER: "msalsouri"  # Replace with your SSH username
          REMOTE_PORT: 2222  # Use the new port number
          TARGET: "/var/www/html/"  # Change this if you want to deploy to a different directory

